# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zoltar&#39;s Magic Answers

description: > # this means to ignore newlines until "baseurl:"
  Sample site using a random number generator activated by a click in jquery to operate the wisdom of Zoltar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "magiceight.sarahbinion.com" # the base hostname & protocol for your site
github_username:  srhbinion
github_username2:  vince-bright

# Build settings
markdown: kramdown
